[versions]

[libraries]
junit = "junit:junit:4.13.2"
robolectric = "org.robolectric:robolectric:4.16.1"

[plugins]
android-application = "com.android.application:9.0.0"
paparazzi = "app.cash.paparazzi:2.0.0-alpha04"
