[versions]
agp = "9.0.0-rc01"
kotlin = "2.2.20"
junit = "4.13.2"
junitVersion = "1.3.0"
robolectric = "4.16"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
paparazzi = "app.cash.paparazzi:2.0.0-alpha02"
